### ISSUE TITLE
Upgrade jackson-databind in Main Standalone Jar 

### ISSUE THREAD

**Issue by mn-mikke** [h2oai/h2o-3#15748]
The current version has the following vulnerabilities.:
- PRISMA-2023-0067

**Comment by mn-mikke** [comment]
This feature will require support for Java 19. Putting on hold for now.

**Comment by wendycwong** [comment]
Hello, I am building an application using h2o but my container scanner has flagged a vulnerability for one of your Java dependencies (com.fasterxml.jackson.core). Could you please bump the version from 2.14.2 to 2.15.0 in the next release? Below you will see the output of the scanner. Thanks!

"vulnerabilities": [
{
"CVE": "PRISMA-2023-0067",
"CVSS": "7.50",
"Fixed On": "24 Apr 23 00:00 UTC",
"Link": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=PRISMA-2023-0067",
"Package Name": "com.fasterxml.jackson.core_jackson-core",
"Package Type": "Java",
"Package Version": "2.14.2",
"Severity": "high",
"Status": "fixed in 2.15.0"
}]

support ticket: https://support.h2o.ai/a/tickets/107321
