### ISSUE TITLE
Problem with tweedie dispersion parameter estimation, AIC, loglikelihood

### ISSUE THREAD

**Issue by wendycwong** [h2oai/h2o-3#15891]
Support ticket: https://support.h2o.ai/a/tickets/106503

We did some tests following the instructions by simulating a dataset with Tweedie distribution and log link.
By setting the “calc_like” parameter to be “TRUE”, the AIC in the model output is no longer “NaN” but a large negative number, which is very suspicious. I also checked the loglikelihood output, which should be a negative number but the model stored LL is a large positive number.  
I tested all three dispersion parameter estimation methods, they showed very different estimation outcomes (ml: 72; Pearson:8913; Deviance: 100). The benchmark I used to simulate the data was 100. I wonder which result was used to calculated AIC or the full likelihood? Is the dispersion parameter estimated together with variable coefficients or separately?
Do you mind pointing us to the codes calculating saturated model deviance for Tweedie GLM?
I attached the test R code above. Please let us know if you have any questions.  

Please get the R code from the support ticket.

**Comment by wendycwong** [comment]
I made minor changes to the code you have and skipped the way you generate the dataset, here is my code:
  ############################### fit R base glm ########################################
   fitBase <- glm(yr~xt, family=tweedie(var.power=1.6, link.power=0), data=simData, weights = weight, offset=offset_col)
  print("Fitting with R")
   print(summary(fitBase)$AIC)
   print(summary(fitBase)$dispersion)
   AICtweedie(fitBase)
  
  
  ###### different dispersion methods using h2o.glm ######
  
  ### deviance ###
  fitH2Otest1 <- h2o.glm(
    remove_collinear_columns=TRUE,
    training_frame = simDataH2O,
    x = 'xt',
    y = 'yr',
    family = "tweedie",
    link = "tweedie",
    tweedie_variance_power = tweedie_p,
    lambda = 0,
    compute_p_values = p_valueAIC,
    calc_like=TRUE,
    dispersion_parameter_method = "deviance"
  ) # options: deviance; ml; pearson
  
   print("deviance dispersion parameter")
  dispersiontest1 <- fitH2Otest1@model$dispersion
  print(dispersiontest1)
  print("loglikelihood from function call")
  print(h2o.loglikelihood(fitH2Otest1, train=TRUE))
  print("AIC from function call")
  print(h2o.aic(fitH2Otest1, train=TRUE))
  
  ### ml ###
  fitH2Otest2 <- h2o.glm(
    remove_collinear_columns=TRUE,
    training_frame = simDataH2O,
    x = 'xt',
    y = 'yr',
    family = "tweedie",
    link = "tweedie",
    tweedie_variance_power = tweedie_p,
    lambda = 0,
    compute_p_values = p_valueAIC,
    dispersion_parameter_method = "ml",
    calc_like=TRUE
  ) # options: deviance; ml; pearson
  
  print("ml with fixed variance power dispersion parameter")
  dispersiontest2 <- fitH2Otest2@model$dispersion
  print(dispersiontest2)
  print("loglikelihood from function call")
  print(h2o.loglikelihood(fitH2Otest2, train=TRUE))
  print("AIC from function call")
  print(h2o.aic(fitH2Otest2, train=TRUE))
  
  ###### different dispersion methods ######
  
  ### pearson ###
  fitH2Otest3 <- h2o.glm(
    remove_collinear_columns=TRUE,
    training_frame = simDataH2O,
    x = 'xt',
    y = 'yr',
    family = "tweedie",
    link = "tweedie",
    tweedie_variance_power = tweedie_p,
    lambda = 0,
    compute_p_values = p_valueAIC,
    dispersion_parameter_method = "pearson",
    calc_like = TRUE
  ) # options: deviance; ml; pearson
  
  print("Pearson dispersion parameter")
  dispersiontest3 <- fitH2Otest3@model$dispersion
  print(dispersiontest3)
  print("loglikelihood from function call")
  print(h2o.loglikelihood(fitH2Otest3, train=TRUE))
  print("AIC from function call")
  print(h2o.aic(fitH2Otest3, train=TRUE))

**Comment by wendycwong** [comment]
Here is the result of one run:
![image](https://github.com/h2oai/h2o-3/assets/7231712/ba1a201f-21a2-4b7d-932e-9ca4a15ad2ab)

**Comment by wendycwong** [comment]
@syzonyuliia :  Please checkout my branch wendy_gh_15891_tweedie_disparameter_rel and see why the calculation of AIC is so off compared to the loglikelihood value and run the test: runit_gh_15891_tweedie_dispersion_parameter_estimation.R in h2o-3/h2o-r/tests/testdir_algos/glm directory.

**Comment by wendycwong** [comment]
Here are multiple runs of the code with different random seed: 
![image](https://github.com/h2oai/h2o-3/assets/7231712/05265840-86ec-4813-9c95-7cf63039be19)

**Comment by tomasfryda** [comment]
@wendycwong are you using the same code to generate the data? The code I used generated data with dispersion = 100.

with that I get a R glm with the following results:
```r
> print(summary(fitBase)$dispersion)
[1] 100.2354
> AICtweedie(fitBase, dispersion = summary(fitBase)$dispersion)
[1] 87146.55
```
---

## I identified 3 issues - one with evaluation (`AICtweedie`) and 2 with H2O:
- `AICtweedie` does a cheap estimate of dispersion even if it's available so it has to be provided as second argument otherwise we get wrong AIC (87710.31 vs 87145.45).  
The dispersion estimation is basically:
```r
        dev <- deviance(glm.obj)
        disp <- dev/sum(wt)
```
- wrong calculation of AIC (${\displaystyle \mathrm {AIC} =2k-2\ln({\hat {L}})}$) - we use neg.log likelihood instead of log likelihood so we need to switch the `-` for `+`

- wrong estimation of the dispersion parameter - when we use the case where we estimate both var.power and dispersion we get more reasonable results (but in much longer time) 

I used `tweedie.profile` to estimate both var.power and dispersion (very time consuming) and then compared the log likelihood (roughly same except for the sign) and AIC (wrong due to the wrong sign from the likelihood).

```r
> fitH2Otest2 <- h2o.glm(
+   remove_collinear_columns=TRUE,
+   training_frame = simDataH2O,
+   x = 'xt',
+   y = 'yr',
+   family = "tweedie",
+   link = "tweedie",
+   tweedie_variance_power = tweedie_p,
+   lambda = 0,
+   compute_p_values = p_valueAIC,
+   dispersion_parameter_method = "ml",
+   calc_like=TRUE,
+   fix_tweedie_variance_power = F,
+   tweedie_link_power = 0
+ )
Warning in .h2o.processResponseWarnings(res) :
  Response contains zeros and/or values lower than zero. Tweedie variance power ML estimation will be limited between 1 and 2. Values lower than zero will be ignored..

  |=========================================================================================================================================================================| 100%
> print("ml with  variance power dispersion parameter")
[1] "ml with  variance power dispersion parameter"
> print("var. power")
[1] "var. power"
> print(fitH2Otest2@params$actual$tweedie_variance_power)
[1] 1.603878
> print("dispersion")
[1] "dispersion"
> dispersiontest2 <- fitH2Otest2@model$dispersion
> print(dispersiontest2)
[1] 98.43553
> print("loglikelihood from function call")
[1] "loglikelihood from function call"
> print(h2o.loglikelihood(fitH2Otest2, train=TRUE))
[1] 43570.72
> print("AIC from function call")
[1] "AIC from function call"
> print(h2o.aic(fitH2Otest2, train=TRUE))
[1] -87137.45
> twp <- tweedie.profile(yr~xt, data = simData, fit.glm = T, p.vec = seq(1.5, 1.8, by=0.001))                       
Warning in model.matrix.default(mt, mf, contrasts) :
  non-list contrasts argument ignored
1.5 1.501 1.502 1.503 1.504 1.505 1.506 1.507 1.508 1.509 1.51 1.511 1.512 1.513 1.514 1.515 1.516 1.517 1.518 1.519 1.52 1.521 1.522 1.523 1.524 1.525 1.526 1.527 1.528 1.529 1.53 1.531 1.532 1.533 1.534 1.535 1.536 1.537 1.538 1.539 1.54 1.541 1.542 1.543 1.544 1.545 1.546 1.547 1.548 1.549 1.55 1.551 1.552 1.553 1.554 1.555 1.556 1.557 1.558 1.559 1.56 1.561 1.562 1.563 1.564 1.565 1.566 1.567 1.568 1.569 1.57 1.571 1.572 1.573 1.574 1.575 1.576 1.577 1.578 1.579 1.58 1.581 1.582 1.583 1.584 1.585 1.586 1.587 1.588 1.589 1.59 1.591 1.592 1.593 1.594 1.595 1.596 1.597 1.598 1.599 1.6 1.601 1.602 1.603 1.604 1.605 1.606 1.607 1.608 1.609 1.61 1.611 1.612 1.613 1.614 1.615 1.616 1.617 1.618 1.619 1.62 1.621 1.622 1.623 1.624 1.625 1.626 1.627 1.628 1.629 1.63 1.631 1.632 1.633 1.634 1.635 1.636 1.637 1.638 1.639 1.64 1.641 1.642 1.643 1.644 1.645 1.646 1.647 1.648 1.649 1.65 1.651 1.652 1.653 1.654 1.655 1.656 1.657 1.658 1.659 1.66 1.661 1.662 1.663 1.664 1.665 1.666 1.667 1.668 1.669 1.67 1.671 1.672 1.673 1.674 1.675 1.676 1.677 1.678 1.679 1.68 1.681 1.682 1.683 1.684 1.685 1.686 1.687 1.688 1.689 1.69 1.691 1.692 1.693 1.694 1.695 1.696 1.697 1.698 1.699 1.7 1.701 1.702 1.703 1.704 1.705 1.706 1.707 1.708 1.709 1.71 1.711 1.712 1.713 1.714 1.715 1.716 1.717 1.718 1.719 1.72 1.721 1.722 1.723 1.724 1.725 1.726 1.727 1.728 1.729 1.73 1.731 1.732 1.733 1.734 1.735 1.736 1.737 1.738 1.739 1.74 1.741 1.742 1.743 1.744 1.745 1.746 1.747 1.748 1.749 1.75 1.751 1.752 1.753 1.754 1.755 1.756 1.757 1.758 1.759 1.76 1.761 1.762 1.763 1.764 1.765 1.766 1.767 1.768 1.769 1.77 1.771 1.772 1.773 1.774 1.775 1.776 1.777 1.778 1.779 1.78 1.781 1.782 1.783 1.784 1.785 1.786 1.787 1.788 1.789 1.79 1.791 1.792 1.793 1.794 1.795 1.796 1.797 1.798 1.799 1.8 
............................................................................................................................................................................................................................................................................................................Warning: glm.fit: algorithm did not converge
.Warning: glm.fit: algorithm did not converge
Done.
> twp$p.max
[1] 1.604082
> twp$phi.max
[1] 98.31162
> twp$L.max
[1] -43570.73
> AICtweedie(twp$glm.obj, dispersion = twp$phi.max)
[1] 87145.45
> 
> # we calculate the AIC by the definition (2*k - 2*logLikelihood) but our log likelihood is actually negative log likelihood
> 2*nrow(fitH2Otest2@model$coefficients_table) - 2*h2o.loglikelihood(fitH2Otest2) # WRONG CALCULATION
[1] -87137.45
> 2*nrow(fitH2Otest2@model$coefficients_table) - 2*-abs(h2o.loglikelihood(fitH2Otest2)) # CORRECT CALCULATION
[1] 87145.45
> 2*nrow(fitH2Otest2@model$coefficients_table) + 2*h2o.loglikelihood(fitH2Otest2) # CORRECT CALCULATION
[1] 87145.45
```
---

## So we need to fix:
- AIC calculation (just switch the sign of log likelihood in the AIC calculation) @syzonyuliia 
- estimation of only the dispersion - I think it's caused by the noise that is caused by limited precision in the likelihood (and grad likelihood) estimation which can make Newton's method jump far from the true value and get stuck between two peaks that exist only due to the noise (at least that's what I saw when working on var. power estimation) @wendycwong

**Comment by wendycwong** [comment]
@tomasfryda :

I ran their code without setting the seed because my R studio will not allow it...   I set the tweedie variance power = 1.6, use maximum likelihood dispersion parameter estimation.

Here is my code:
############################### fit R base glm ########################################
fitBase <- glm(yr~xt, family=tweedie(var.power=1.6, link.power=0), data=simData, weights = weight, offset=offset_col)
print("Fitting with R")
print(summary(fitBase)$AIC)
print(summary(fitBase)$dispersion)
AICtweedie(fitBase)

different dispersion methods using h2o.glm

deviance

fitH2Otest1 <- h2o.glm(
remove_collinear_columns=TRUE,
training_frame = simDataH2O,
x = 'xt',
y = 'yr',
family = "tweedie",
link = "tweedie",
tweedie_variance_power = tweedie_p,
lambda = 0,
compute_p_values = p_valueAIC,
calc_like=TRUE,
dispersion_parameter_method = "deviance"
) # options: deviance; ml; pearson

print("deviance dispersion parameter")
dispersiontest1 <- fitH2Otest1@model$dispersion
print(dispersiontest1)
print("loglikelihood from function call")
print(h2o.loglikelihood(fitH2Otest1, train=TRUE))
print("AIC from function call")
print(h2o.aic(fitH2Otest1, train=TRUE))

ml

fitH2Otest2 <- h2o.glm(
remove_collinear_columns=TRUE,
training_frame = simDataH2O,
x = 'xt',
y = 'yr',
family = "tweedie",
link = "tweedie",
tweedie_variance_power = tweedie_p,
lambda = 0,
compute_p_values = p_valueAIC,
dispersion_parameter_method = "ml",
calc_like=TRUE
) # options: deviance; ml; pearson

print("ml with fixed variance power dispersion parameter")
dispersiontest2 <- fitH2Otest2@model$dispersion
print(dispersiontest2)
print("loglikelihood from function call")
print(h2o.loglikelihood(fitH2Otest2, train=TRUE))
print("AIC from function call")
print(h2o.aic(fitH2Otest2, train=TRUE))

different dispersion methods

pearson

fitH2Otest3 <- h2o.glm(
remove_collinear_columns=TRUE,
training_frame = simDataH2O,
x = 'xt',
y = 'yr',
family = "tweedie",
link = "tweedie",
tweedie_variance_power = tweedie_p,
lambda = 0,
compute_p_values = p_valueAIC,
dispersion_parameter_method = "pearson",
calc_like = TRUE
) # options: deviance; ml; pearson

print("Pearson dispersion parameter")
dispersiontest3 <- fitH2Otest3@model$dispersion
print(dispersiontest3)
print("loglikelihood from function call")
print(h2o.loglikelihood(fitH2Otest3, train=TRUE))
print("AIC from function call")
print(h2o.aic(fitH2Otest3, train=TRUE))

**Comment by wendycwong** [comment]
@tomasfryda :  Since we know the tweedie_variance_power, I set it to the correct value of 1.6 and fix_tweedie_variance_power=TRUE.  I think that is the reason you are getting a different result.

**Comment by tomasfryda** [comment]
@wendycwong yes, I'm aware that we know the Tweedie variance power. I set the `fix_tweedie_variance_power=FALSE` in order to use the different estimation algorithm that is hopefully more robust.

With `fix_tweedie_variance_power=FALSE`, we use different optimization algorithm (Newton's method didn't converge in most cases) and also different calculation of likelihood - I used the combination of the series and the Fourier inverse methods (based on some heuristic that's used also in the R's package `tweedie`).

I think the fixing just the optimization part would help without the need to change the likelihood estimation. The likelihood is a little bit noisy but I don't think that's the problem - the problem is I think that the noisy in the likelihood can create huge gradients and hessians (at least that's what was happening when I was implementing the Tweedie variance power estimation).

----

> I ran their code without setting the seed because my R studio will not allow it...

I think you should be able to set the seed using the `set.seed(1234)` command. What error does the RStudio throw?

> @tomasfryda : Since we know the tweedie_variance_power, I set it to the correct value of 1.6 and fix_tweedie_variance_power=TRUE. I think that is the reason you are getting a different result.

Yes, but it's also important to check if our estimate works as expected. We should get the true value if we'd have infinite amount of data but we don't so I think we should be more interested in how close our estimate is to the correct estimate not the true value. So I think we should also compare with the results of the `tweedie` package (or any other trustworthy implementation).

For example:

Lets take a 10k observations from $\mathcal{N}(0, 1)$, we know it should have the `mean = 0` but should we benchmark our ML estimation with 0 or the ML estimation of mean of that sample? I  think it's better to compare with the estimation that we consider correct. If we'd get result like `-0.046` that could seem too off from our expected mean 0 given that we have 10k observations but it can still be a correct estimation:

```r
> set.seed(49559)
> summary(rnorm(10000))

    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.
-3.95706 -0.73520 -0.05675 -0.04648  0.62562  3.89973
```

And if we'd try to make our implementation to estimate the mean to 0 we'd likely make a more biased estimator.

**NOTE:** Be sure to read the man pages, in the `tweedie` package they sometimes speed up the things by using heuristic (e.g. guessing dispersion from deviance) and then you can spend a lot of time debugging a non-existent issue (yes, that happened to me).

**Comment by wendycwong** [comment]
Okay, I will fix the dispersion parameter calculation part.  Thank you Tomas in pointing that out!
