### ISSUE TITLE
Plotting H2O Decision Trees in R

### ISSUE THREAD

**Issue by dmresearch15** [h2oai/h2o-3#16090]
In the provided example from https://h2o.ai/blog/2019/finally-you-can-plot-h2o-decision-trees-in-r/ , one of the decision tree rules are described as follows:

If title  = Mr, Officer and cabin_type = F, T, NA and Age (L) >= 30.26, NA then (Age < 30.94 or Age >= 30.94, NA) and so on.
The goal is to understand the conditions under which the Age(L) and later Age are determined within the decision tree. 

Alternatively, I’m trying to find the difference between Age(L) and the later Age.

**Comment by wendycwong** [comment]
Can you give us an example of what you are looking for?  What do you mean by difference?  Difference in threshold values, final class probabilities or something else?  Thanks.

**Comment by dmresearch15** [comment]
For instance, on the website (https://h2o.ai/blog/2019/finally-you-can-plot-h2o-decision-trees-in-r/), I'm endeavouring to grasp the distinctions between age(L), age(R), and age, as illustrated.

**Comment by wendycwong** [comment]
User is trying to understand the decision tree graph.

**Comment by maurever** [comment]
Hi, @dmresearch15, thanks for your question. 

We used the titles Age(L) and Age(R) for node names because they come from one parent node and use the same variable for the next split. It is to distinguish them in the graph. The variable is still the same for the whole tree; only the values of the variable change based on the split.
